### ISSUE TITLE
axes d'amélioration:

### ISSUE THREAD

**Issue by titouwork** [WildCodeSchool/2023-03-remote-fr-php-origins-digital#100]
il y a beaucoup de points d'amélioration: 
- un site plus performant, 
- modification des routes: des fois je vais dans category/2/3 c'est moche, 
- en dehors de l'ajout de favoris et l'accessibilité, il faudrait rajouter d'autres bonus pour inciter les gens à s'inscrire,

**Comment by BrianV87** [comment]
Peut tu donner des pistes à l'équipe technique afin d'avoir un site plus performant ?
Les routes sont actuellement en cour de changement dans un pr proche.
Peut tu nous donner des idées pour inciter les gens à s'inscrire ?
