### ISSUE TITLE
Lien FAQ

### ISSUE THREAD

**Issue by Karabuff** [WildCodeSchool/2023-03-remote-fr-php-origins-digital#98]
Le lien de la FAQ dans le footer ne mene à rien.
Mis à part ca bien joué :)

**Comment by BrianV87** [comment]
C'est dans la prochaine pr en attente de validation :'(

**Comment by Karabuff** [comment]
Ah vous aussi vous avez des soucis avec votre validateur de PR ? xD

**Comment by BrianV87** [comment]
Exactement mdr, des fois il part en vacance xD
